# Generated by Django 2.0.3 on 2018-09-17 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='lançe')),
                ('bought', models.BooleanField(default=False, verbose_name='comprado')),
            ],
            options={
                'verbose_name_plural': 'lançes',
                'verbose_name': 'lançe',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('keyword', models.CharField(max_length=255, verbose_name='palavra chave')),
                ('startPrice', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='lançe inicial')),
                ('ultimoLance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='lançe final')),
                ('Prazo', models.DateField(verbose_name='prazo')),
                ('vendido', models.BooleanField(default=False, verbose_name='vendido')),
                ('compradoPor', models.CharField(max_length=255, verbose_name='nomeComprador')),
                ('state', models.BooleanField(default=True, verbose_name='ativo')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'produtos',
                'verbose_name': 'produto',
            },
        ),
        migrations.AddField(
            model_name='lance',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leilao.Produto'),
        ),
        migrations.AddField(
            model_name='lance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
